schema_version: 1

context:
  name: azure-mgmt-extendedlocation
  version: 1.0.0b2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure-mgmt-extendedlocation-${{ version }}.zip
  sha256: 9a37c7df94fcd4943dee35601255a667c3f93305d5c5942ffd024a34b4b74fc0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1,<2.0
    - azure-mgmt-core >=1.2.0,<2.0
    - msrest >=0.6.21

tests:
  - python:
      imports:
        - azure.mgmt.extendedlocation
        - azure.mgmt.extendedlocation.aio
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure Extended Location Management Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
